import type { InventoryItem } from "./types";

export const DUMMY_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "1",
    periodMonth: "01",
    periodYear: "2025",
    typeOfStocks: "Beginning Stocks",
    typeOfVatTaxpayer: "VAT Registered",
    supplierName: "Supplier A",
    tinNo: "123-456-789-000",
    productNameSpecific: "Bond Paper A4 80gsm",
    productNameGeneral: "Paper",
    itemCode: "BP-A4-80",
    accountingRecognition: "Office Supplies",
    measurement: "ream",
    quantity: 10,
    unitPrice: 420,
    totalPrice: 4200,
    vatable: 3750,
    vat: 450,
    ewt: 75,
    netPay: 4125,
  },
  {
    id: "2",
    periodMonth: "01",
    periodYear: "2025",
    typeOfStocks: "Additional Stocks",
    typeOfVatTaxpayer: "Non-VAT",
    supplierName: "Supplier B",
    tinNo: "987-654-321-000",
    productNameSpecific: "Liquid Soap 1L",
    productNameGeneral: "Janitorial",
    itemCode: "LS-1L",
    accountingRecognition: "Janitorials",
    measurement: "L",
    quantity: 24,
    unitPrice: 85,
    totalPrice: 2040,
    vatable: 2040,
    vat: 0,
    ewt: 0,
    netPay: 2040,
  },
  {
    id: "3",
    periodMonth: "02",
    periodYear: "2025",
    typeOfStocks: "Issued Stocks",
    supplierName: "N/A",
    productNameSpecific: "Bond Paper A4 80gsm",
    productNameGeneral: "Paper",
    itemCode: "BP-A4-80",
    accountingRecognition: "Office Supplies",
    measurement: "ream",
    quantity: 3,
    unitPrice: 420,
    totalPrice: 1260,
    vatable: 1125,
    vat: 135,
    ewt: 22.5,
    netPay: 1237.5,
  },
  {
    id: "4",
    periodMonth: "02",
    periodYear: "2025",
    typeOfStocks: "Additional Stocks",
    typeOfVatTaxpayer: "VAT Registered",
    supplierName: "Supplier C",
    tinNo: "111-222-333-000",
    productNameSpecific: "Ballpen Blue",
    productNameGeneral: "Office Supplies",
    itemCode: "BP-BLUE",
    accountingRecognition: "Office Supplies",
    measurement: "box",
    quantity: 50,
    unitPrice: 120,
    totalPrice: 6000,
    vatable: 5357.14,
    vat: 642.86,
    ewt: 107.14,
    netPay: 5892.86,
  },
  {
    id: "5",
    periodMonth: "01",
    periodYear: "2025",
    typeOfStocks: "Beginning Stocks",
    typeOfVatTaxpayer: "VAT Registered",
    supplierName: "Supplier A",
    tinNo: "123-456-789-000",
    productNameSpecific: "Tissue Roll 2-ply",
    productNameGeneral: "Janitorial",
    itemCode: "TR-2P",
    accountingRecognition: "Janitorials",
    measurement: "pack",
    quantity: 20,
    unitPrice: 65,
    totalPrice: 1300,
    vatable: 1160.71,
    vat: 139.29,
    ewt: 23.21,
    netPay: 1276.79,
  },
];
